logging:
  level:
    org:
      hibernate:
        SQL: INFO
server:
  error:
    whitelabel:
      enabled: true
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 1200000
      maximum-pool-size: 5
      minimum-idle: 2
      pool-name: data-source
    url: jdbc:mysql://localhost:3306/fishstore?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    password: 123456
    username: root
  jackson:
    date-format: MMMM dd yyyy / HH:mm
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        ddl-auto: update

  mvc:
    throw-exception-if-no-handler-found: true

security:
  public-pattern: /api/public/**
  auth:
    username: test
    url: http://localhost:8081/oauth/check_token
    client_id: test
    client_password: test
    connection_timeout: 60
    read_timeout: 60
    whitelist: >
      /,
      /v2/api-docs,
      /swagger-resources,
      /swagger-resources/**,
      /configuration/ui,
      /configuration/security,
      /swagger-ui.html,
      /webjars/**,
      /api/public/**

swagger:
  host:
    address: localhost:8080
    path: /
  api:
    name: Fish store Api Documentation
    version: v1
  contact:
    name: Md Ad
    url:
    email:

